# Generated by Django 3.2 on 2021-06-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210613_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
    ]
