# Generated by Django 3.2 on 2021-06-13 13:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('questions', '0005_remove_questions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
