# Generated by Django 3.2 on 2021-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_title',
            field=models.TextField(default='Default', max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(max_length=500),
        ),
    ]
